import type { Metadata } from "next";
import { Inter } from "next/font/google";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import Header from "@/components/Header";
import GlobalProvider from "@/providers/GlobalProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <GlobalProvider>
          <Header />
          <main className="main-container mt-[20px]">
            {children}
          </main>
        </GlobalProvider>
      </body>
    </html>
  );
}
